### PR TITLE
Converted Turrets To Data

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- Same as in #1 

<br>
<br>

## ![Badge Changes]

- Fixed syntax errors

- Extracted data from turrets

- Added turret-builder

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***,
  *please first let me know about them, before disregarding it entirely so*
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge GitHub]

<br>

*If you are new to **GitHub** and aren't sure how to accept commits,*
*please familiarize yourself with the basics of **Git** / **GitHub** first.*

### Pull Requests

To accept pull requests you simply have to 
press the   <kbd>   Merge PullRequest   </kbd>   button.

***Never Copy-Paste Someones Contribution***, 
*this robs them off their attribution and is thus* 
*just plain copyright theft.*

[Preview]: https://github.com/ElectronicsArchiver/BreakingMindustry

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
If you have a test map, you should probably add it to the repository~

**Comment by driftednotes** [comment]
ah yes

**Comment by ElectronicsArchiver** [comment]
@driftednotes did you read my messages in the previous pull request?

**Comment by driftednotes** [comment]
> @driftednotes did you read my messages in the previous pull request?

yeah, i have read your messages in #1 .

> Btw, you can just set your editors indent level to 8 and leave the codes normalized level at 4 ..

~~but i use github to edit my code.~~
ok. i will leave the indent settings at 4.

> Also why is source.txt, well, a text file to begin with?

yes, i always use it ~~(and by **use(ing) it** i mean copy and paste some code from it)~~ for coding turret scripts.

**Comment by ElectronicsArchiver** [comment]
@driftednotes 

> but i use github to edit my code.

You can also set the indentation level on GitHub, in your appearance settings and when opening a file in the upper left corner

> yes, i always use it (and by use(ing) it i mean copy and paste some code from it) for coding turret scripts.

I assume it's your work though?

**Comment by 12three7** [comment]
> You can also set the indentation level on GitHub, in your appearance settings and when opening a file in the upper left corner

~~i almost forgot that github has that feature~~

**Pull request merged**
